language: python
python:
    - "2.7"

# command to install dependencies
install: pip install -r requirements.txt --use-mirrors
# command to run tests
script: python tests/run

notifications:
    email:
        recipients:
            - nick@nclarkjudd.com
        on_success: change
        on_failure: change