language: python
python:
  - "2.7"

# command to install dependencies
install: pip install -r requirements.txt

# command to run tests
script: python test/run

notifications:
  email:
    recipients: 
      - eric@konklone.com
    on_success: change
    on_failure: change
